version: '3.8'
services:
  configserver:
    container_name: configserver
    build: 
      context: ./NodejsApp
      dockerfile: Dockerfile
    volumes:
      - sqlitedb: /usr/src/app/Database
      - customJSON: /usr/src/app/customJSON
    restart: always
    ports:
      - 4000:4000
  application:
    container_name: application
    build:
      context: ./ReactApp
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3000:3000

db:
  sqlitedb:
  customJSON: